Garage2/Controllers/ServicesController.cs
using Garage2.Models;
using Garage2.Models.Car;
using Garage2.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace Garage2.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IServiceCategoryRepository categoryRepository;
        private readonly IServiceItemRepositiry itemRepositiry;
        private readonly IServiceRepository serviceRepository;
        private readonly ICategoryItemsRepository categoryItemsRepository;
        private readonly UserManager<AppUser> userManager;
        private readonly ICarsRepository carsRepository;

        public ServicesController(IServiceCategoryRepository categoryRepository,
            IServiceItemRepositiry itemRepositiry,
            IServiceRepository serviceRepository,
            ICategoryItemsRepository categoryItemsRepository,
            UserManager<AppUser> userManager,
            ICarsRepository carsRepository
            )
        {
            this.categoryRepository = categoryRepository;
            this.itemRepositiry = itemRepositiry;
            this.serviceRepository = serviceRepository;
            this.categoryItemsRepository = categoryItemsRepository;
            this.userManager = userManager;
            this.carsRepository = carsRepository;
        }

        //  SERVICES

        //Show all users 
        public IActionResult Services(string searchTerm)
        {
            var model = new CarUserViewModel();

            if (searchTerm == null)
            {
                model.AppUsersEnumerable = userManager.Users;
                return View(model);
            }
            else
            {

                model.AppUsersEnumerable = userManager.Users.Where(x => x.UserName.Contains(searchTerm)||
                                                                        x.LastName.Contains(searchTerm)||
                                                                        x.Email.Contains(searchTerm)||
                                                                        x.PhoneNumber.Contains(searchTerm));
                return View(model);
            }
        }

        //Show cars for curent user
        public IActionResult UserCars(string id)
        {
            var model = new CarUserViewModel();
            model.CarsEnumerable = carsRepository.AllCars.Where(x => x.UserId == id);

            ViewBag.curentUser = userManager.Users.FirstOrDefault(x => x.Id == id).UserName;

            return View(model);
        }

        //Show services for selected user car
        public IActionResult ShowServices(int id)
        {
            var model = new ServiceViewModel();
            model.ServiceEnumerable = serviceRepository.AllServices.Where(x => x.CarId == id);

            ViewBag.carModel = carsRepository.AllCars.FirstOrDefault(x => x.Id == id).Model;

            return View(model);
        }
        //Create new service
        [HttpGet]
        public IActionResult NewService(int id)
        {
            if (id == 0)
            {
                ViewBag.CategoryItems = new SelectList(itemRepositiry.AllItems, "Item", "Item", 1, "Category");
                return View("_AddNewService");
            }
            else
            {
                var catItems = categoryItemsRepository.AllCategoryItems.Where(x => x.ServiceId == id).Select(x => x.Items);

                ViewBag.CategoryItems = new MultiSelectList(itemRepositiry.AllItems, "Item", "Item", catItems, "Category");

                var service = serviceRepository.AllServices.FirstOrDefault(x => x.ServiceId == id);

                var model = new ServiceViewModel()
                {
                    Service = service
                };
                return View("_AddNewService", model);
            }
        }


        public IActionResult AddNewService(ServiceViewModel serviceViewModel, string[] array, string returnUrl)
        {
            if (serviceViewModel.Service.ServiceId == 0) // ako je Service.ServiceId = 0 onda kreiraj nov servis ako ne onda ide update
            {
                var service = new Service()
                {
                    ServiceId = serviceViewModel.Service.ServiceId,
                    ServiceDate = serviceViewModel.Service.ServiceDate,
                    Mileage = serviceViewModel.Service.Mileage,
                    ServiceCost = serviceViewModel.Service.ServiceCost,
                    Notes = serviceViewModel.Service.Notes,
                    CarId = serviceViewModel.Service.CarId

                };

                serviceRepository.Add(service);

                foreach (var item in array)
                {
                    var itemId = itemRepositiry.AllItems.Where(x => x.Item == item).FirstOrDefault().ItemId;

                    var cat = itemRepositiry.AllItems.Where(x => x.Item == item).FirstOrDefault().Category;

                    var catId = categoryRepository.AllCategories.Where(x => x.Category == cat).FirstOrDefault().CategoryId;

                    var categoryItem = new CategoryItems()
                    {
                        Items = item,
                        ServiceId = service.ServiceId,
                        ItemId = itemId,
                        CategoryId = catId,
                        Category = cat
                    };

                    categoryItemsRepository.Add(categoryItem);
                }

                return RedirectToAction("ShowServices", new { id = serviceViewModel.Service.CarId });

            }
            else // odavde ide update
            {
                serviceRepository.Update(serviceViewModel.Service); // update service model

                //first delete categories items which we want to update
                var catItemsId = categoryItemsRepository.AllCategoryItems.Where(x => x.ServiceId == serviceViewModel.Service.ServiceId).Select(x => x.Id).ToList(); // need to be toList() in order to delete 

                foreach (var id in catItemsId)
                {
                    categoryItemsRepository.Delete(id);
                }

                //create updated categories items 
                foreach (var item in array)
                {
                    var itemId = itemRepositiry.AllItems.Where(x => x.Item == item).FirstOrDefault().ItemId;

                    var cat = itemRepositiry.AllItems.Where(x => x.Item == item).FirstOrDefault().Category;

                    var catId = categoryRepository.AllCategories.Where(x => x.Category == cat).FirstOrDefault().CategoryId;

                    var categoryItem = new CategoryItems()
                    {
                        Items = item,
                        ServiceId = serviceViewModel.Service.ServiceId,
                        ItemId = itemId,
                        CategoryId = catId,
                        Category = cat
                    };

                    categoryItemsRepository.Add(categoryItem);
                }
            }

            return RedirectToAction("ShowServices", new { id = serviceViewModel.Service.CarId });
        }

        public IActionResult DeleteService(int Id)
        {
            var catItem = categoryItemsRepository.AllCategoryItems.Where(x => x.ServiceId == Id).Select(x => x.Id).ToList();

            foreach (var id in catItem)
            {
                categoryItemsRepository.Delete(id);
            }

            var carId = serviceRepository.AllServices.FirstOrDefault(x => x.ServiceId == Id).CarId;

            serviceRepository.Delete(Id);

            return RedirectToAction("ShowServices", new { id = carId });
        }
    // CUSTOMER SERVICES

        [HttpGet]
        public IActionResult CustomerServices()
        {
            ViewBag.user = userManager.GetUserName(HttpContext.User);

            var userId = userManager.GetUserId(HttpContext.User);
            var usersCar = carsRepository.AllCars.Where(x => x.UserId == userId && x.IsActive == true);
            ViewBag.userCars = new SelectList(usersCar,"Id","Model");

            return View();
        }

        [HttpPost]
        public IActionResult CustomerServices(int id)
        {
            ViewBag.user = userManager.GetUserName(HttpContext.User);

            var userId = userManager.GetUserId(HttpContext.User);
            var usersCar = carsRepository.AllCars.Where(x => x.UserId == userId && x.IsActive == true);
            ViewBag.userCars = new SelectList(usersCar, "Id", "Model");

            ViewBag.selectedCar = carsRepository.AllCars.FirstOrDefault(x => x.Id == id).Model;

            var model = new ServiceViewModel();
            model.ServiceEnumerable = serviceRepository.AllServices.Where(x => x.CarId == id);
            return View(model);
        }

      
        public IActionResult ServiceDetails(int id)
        {            
            var model = categoryItemsRepository.AllCategoryItems.Where(x => x.ServiceId == id);
            return View("_ServiceDetails", model );
        }


    }
}






/*
 
 */

Garage2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Garage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">      <!--https://developer.snapappointments.com/bootstrap-select/-->
</head>
<body>
    <header>
        @await Html.PartialAsync("_NavBar");
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Modal placeholder -->
    <div id="modal-placeholder"></div>

    <!-- Modal for add new service -->
    <div class="modal" tabindex="-1" id="form-modal">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>

            </div>
        </div>
    </div>
    <!-- Modal for add new car -->
    <div class="modal" tabindex="-1" id="car-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>

            </div>
        </div>
    </div>




    @{await Html.RenderPartialAsync("_RegisterModalPartialView", new RegisterViewModel());}


    @{await Html.RenderPartialAsync("_LoginModalPartialView", new LoginViewModel());}



    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Garage2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Garage2/Views/Shared/_LoginModalPartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model LoginViewModel

<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="Account/_LoginModalPartialView">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" id="email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" id="nesto"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label asp-for="RememberMe">
                                <input asp-for="RememberMe" />
                                @Html.DisplayNameFor(m => m.RememberMe)
                            </label>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-outline-primary" data-login="modalLogin">Login</button>
            </div>
        </div>
    </div>
</div>

Garage2/Views/Shared/_NavBar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> signInManager

    <div class="container mt-2 mb-0">
        
            <div class="row">
                <i class="bi bi-telephone mr-1"></i>
                <p class="mr-2">+381-026-123-456</p>
                <i class="bi bi-geo-alt mr-1"></i>
                <p>Drvarska 1, Smederevo</p>
            </div>
    </div>


<nav class="navbar navbar-expand-sm navbar-toggleable-sm mb-3">
    <div class="container">
        @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Garage</a>*@
        <img src="~/images/Logo-Karic-CB.png" class="img-thumbnail border-0" style="max-width:10%" alt="...">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">

                @if (signInManager.IsSignedIn(User) && User.IsInRole("User"))                            //www.youtube.com/watch?v=YLAHIZmO2PI
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="CustomerServices">Your Service</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" id="logout" asp-area="" asp-controller="Account" asp-action="Logout">Logout  @User.Identity.Name</a>
                    </li>
                }
                else if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Categories">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="admin" asp-action="Users">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" id="logout" asp-area="" asp-controller="Account" asp-action="Logout">Logout  @User.Identity.Name</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" id="registerModal" data-toggle="ajax-modal" data-target="#add-contact" data-url="@Url.ActionLink("_RegisterModalPartialView","Account")">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" id="loginModal" data-toggle="ajax-modal" data-target="#add-contact" data-url="@Url.ActionLink("_LoginModalPartialView","Account")">Login</a>
                    </li>
                }

            </ul>
        </div>
    </div>
</nav>


<style>
    a{
        font-size:1.25rem
    }
</style>

Garage2/Views/Shared/_RegisterModalPartialView.cshtml
@model RegisterViewModel



<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addContactLabel">User registration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="Account/_RegisterModalPartialView">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <div class="form-group">
                        <label asp-for="FirstName"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber"></label>
                        <input asp-for="PhoneNumber" class="form-control"/>
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LicencePlate"></label>
                        <input asp-for="LicencePlate" class="form-control" />
                        <span asp-validation-for="LicencePlate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword"></label>
                        <input asp-for="ConfirmPassword" class="form-control" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-outline-primary" data-save="modal">Register</button>
            </div>
        </div>
    </div>
</div>




















@*<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">User registration</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                            <form asp-action="_RegisterModalPartialView">
                                <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

                                <div class="form-group">
                                    <label asp-for="Email"></label>
                                    <input asp-for="Email" class="form-control" required />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Password"></label>
                                    <input asp-for="Password" class="form-control" required />
                                    <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ConfirmPassword"></label>
                                    <input asp-for="ConfirmPassword" class="form-control" required />
                                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                </div>
                            </form>


                </div>
                <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" data-save="modal">Save changes</button>
                    </div>
            </div>
        </div>
    </div>*@